# Generated by Django 5.1.15 on 2026-10-09 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0011_eventrequest_registration_capacity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("accessibility_needs", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("WAITLISTED", "On waiting list"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                ("waitlisted_at", models.DateTimeField(blank=True, null=True)),
                ("place_offered_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.eventrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["REGISTERED", "WAITLISTED"])),
                        fields=("event", "attendee"),
                        name="one_active_registration_per_attendee",
                    )
                ],
            },
        ),
    ]
