# Generated by Django 5.1.15 on 2026-09-28 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventrequest_approval"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="unique_assignment_notification",
        ),
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[("ASSIGNMENT", "Coordinator assigned"), ("APPROVED", "Request approved")],
                default="ASSIGNMENT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "event", "kind"), name="unique_notification_per_kind"
            ),
        ),
    ]
