# Generated by Django 5.1.15 on 2026-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notification_rejected_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ASSIGNMENT", "Coordinator assigned"),
                    ("APPROVED", "Request approved"),
                    ("CLARIFICATION", "Clarification requested"),
                    ("RESUBMITTED", "Request resubmitted"),
                    ("REJECTED", "Request rejected"),
                    ("STATUS_CHANGED", "Event status changed"),
                ],
                default="ASSIGNMENT",
                max_length=20,
            ),
        ),
    ]
