# Generated by Django 5.1.15 on 2026-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ASSIGNMENT", "Coordinator assigned"),
                    ("APPROVED", "Request approved"),
                    ("CLARIFICATION", "Clarification requested"),
                    ("RESUBMITTED", "Request resubmitted"),
                    ("REJECTED", "Request rejected"),
                    ("STATUS_CHANGED", "Event status changed"),
                    ("REASSIGNED", "Coordinator reassigned"),
                    ("BOOKING_REQUESTED", "Venue booking requested"),
                    ("BOOKING_DECIDED", "Venue booking decided"),
                    ("BOOKING_WITHDRAWN", "Venue booking withdrawn"),
                ],
                default="ASSIGNMENT",
                max_length=20,
            ),
        ),
    ]
