# Generated by Django 5.1.15 on 2026-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ASSIGNMENT", "Coordinator assigned"),
                    ("APPROVED", "Request approved"),
                    ("CLARIFICATION", "Clarification requested"),
                    ("RESUBMITTED", "Request resubmitted"),
                    ("REJECTED", "Request rejected"),
                    ("STATUS_CHANGED", "Event status changed"),
                    ("REASSIGNED", "Coordinator reassigned"),
                    ("BOOKING_REQUESTED", "Venue booking requested"),
                    ("BOOKING_DECIDED", "Venue booking decided"),
                    ("BOOKING_WITHDRAWN", "Venue booking withdrawn"),
                    ("EQUIPMENT_REQUESTED", "Equipment requested"),
                    ("EQUIPMENT_CHANGED", "Equipment request changed"),
                    ("EQUIPMENT_RESERVED", "Equipment reserved"),
                    ("EQUIPMENT_RELEASED", "Equipment released"),
                    ("REGISTERED", "Registration confirmed"),
                    ("WAITLISTED", "Added to waiting list"),
                    ("UNREGISTERED", "Registration withdrawn"),
                    ("PLACE_AVAILABLE", "Place available"),
                    ("EVENT_FULL", "Registration full"),
                    ("CHANGE_REQUESTED", "Change requested"),
                    ("CHANGE_DECIDED", "Change request decided"),
                    ("EVENT_CHANGED", "Event details changed"),
                    ("REVIEW_NEEDED", "Arrangement needs review"),
                    ("REVIEW_OUTCOME", "Arrangement reviewed"),
                ],
                default="ASSIGNMENT",
                max_length=20,
            ),
        ),
    ]
