# Generated by Django 5.1.15 on 2026-09-19 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("purpose", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("preferred_start", models.DateTimeField(blank=True, null=True)),
                ("preferred_end", models.DateTimeField(blank=True, null=True)),
                ("expected_attendance", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "required_layout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("THEATRE", "Theatre"),
                            ("BOARDROOM", "Boardroom"),
                            ("BANQUET", "Banquet"),
                            ("EXHIBITION", "Exhibition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accessibility_needs", models.TextField(blank=True)),
                ("equipment_notes", models.TextField(blank=True)),
                ("registration_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("PLANNING", "Planning"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_event_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_event_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_requests",
                        to="accounts.clientorganisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("PLANNING", "Planning"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("PLANNING", "Planning"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="events.eventrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "event status history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eventrequest",
            index=models.Index(
                fields=["status", "submitted_at"], name="events_even_status_c9ce5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventrequest",
            index=models.Index(
                fields=["organisation", "status"], name="events_even_organis_4b66da_idx"
            ),
        ),
    ]
