# Generated by Django 5.1.15 on 2026-09-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_eventrequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="assignment_requires_attention",
            field=models.BooleanField(default=False),
        ),
    ]
