# Generated by Django 5.1.15 on 2026-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_eventrequest_rejection"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
    ]
