# Generated by Django 5.1.15 on 2026-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_eventrequest_confirmed_at_eventrequest_confirmed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="registration_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrequest",
            name="registration_closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrequest",
            name="registration_opens_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrequest",
            name="waitlist_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
