# Generated by Django 5.1.15 on 2026-10-09 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_eventrequest_registration_capacity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("reason", models.TextField(blank=True)),
                ("proposed_start", models.DateTimeField(blank=True, null=True)),
                ("proposed_end", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_attendance",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "proposed_layout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("THEATRE", "Theatre"),
                            ("BOARDROOM", "Boardroom"),
                            ("BANQUET", "Banquet"),
                            ("EXHIBITION", "Exhibition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("proposed_accessibility_needs", models.TextField(blank=True)),
                ("proposed_equipment_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="events.eventrequest",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
