# Generated by Django 5.1.15 on 2026-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentrequest",
            name="unavailable_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="equipmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("RESERVED", "Reserved"),
                    ("UNAVAILABLE", "Unavailable"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
    ]
