# Generated by Django 5.1.15 on 2026-09-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coordinator_available",
            field=models.BooleanField(
                default=True,
                help_text="Available for automatic event assignment (coordinators only).",
            ),
        ),
    ]
